# External/Galaxy roles
#
# Import new role definitions by issuing: ansible-galaxy install -r requirements.yml
#

- src: https://github.com/corford/ansible-role-docker
  version: master
  name: EXT.docker

- src: https://github.com/corford/ansible-role-redis-multi-instance
  version: master
  name: EXT.redis-multi

- src: https://github.com/corford/ansible-role-nodejs
  version: master
  name: EXT.nodejs
